on:
  push:
    branches:
      - main  
    tags:
      - v*

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Build Frontend Docker Image
      run: |
        chmod +x ./build_frontend.sh
        ./build_frontend.sh
    
    - name: Tag Frontend Docker Image
      run: |
        docker tag dwarf-frontend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/dwarf-frontend:latest   
        
    - name: Push Frontend Docker Image
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/dwarf-frontend:latest
    
    - name: Force Deploy of Frontend Service
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws ecs update-service --cluster dwarf-cluster --service dwarf-frontend-service-2 --force-new-deployment --debug --region ${{ secrets.AWS_REGION }}
    
      